FROM bitnami/spark:latest

RUN pip install --no-cache-dir --trusted-host pypi.org --trusted-host files.pythonhosted.org --cert /etc/ssl/certs/ca-certificates.crt pandas py4j || \
    pip install --no-cache-dir --trusted-host pypi.org --trusted-host files.pythonhosted.org --disable-pip-version-check --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org --trusted-host pypi.org --index-url=http://pypi.org/simple/ pandas py4j

